# Generated by Django 3.0.3 on 2020-02-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=100)),
                ('Develop_By', models.CharField(max_length=100)),
                ('Develop_For', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
            ],
        ),
    ]
