# Generated by Django 3.0.3 on 2020-02-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'University'), (2, 'Company'), (3, 'Select Category')], default=3)),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('website', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('user', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('email_verify', models.BooleanField(default=False)),
                ('phone_verify', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
