# Generated by Django 2.2.7 on 2020-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('Sub_category', models.CharField(max_length=200)),
                ('durations', models.CharField(max_length=200)),
                ('bidding', models.CharField(max_length=200)),
            ],
        ),
    ]
