# Generated by Django 2.2.7 on 2020-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.CharField(max_length=30)),
                ('bid_time', models.CharField(max_length=30)),
            ],
        ),
    ]
